# ==========================================
# CONFIGURAÇÕES DO BANCO DE DADOS H2
# ==========================================
# Define a URL do banco em memória (o banco se chamará 'locatedb')
spring.datasource.url=jdbc:h2:mem:locatedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Habilita o painel visual do H2 no navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ==========================================
# CONFIGURAÇÕES DO JPA / HIBERNATE
# ==========================================
# Mostra os comandos SQL no terminal (ótimo para debug e mostrar conhecimento)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Cria e atualiza as tabelas automaticamente com base nas nossas Entidades
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect